# Generated by Django 2.2.4 on 2019-08-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesaApiclient', '0002_auto_20190819_1352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='response',
            new_name='B2CResponse',
        ),
    ]
