# Generated by Django 2.2.4 on 2019-08-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesaApiclient', '0004_auto_20190819_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2cresponse',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
